TYPO3GmbH/blog

README.md
=> [TASK] Improve readme

Classes/ViewHelpers/Link/ArchiveViewHelper.php, Classes/ViewHelpers/Link/AuthorViewHelper.php, Classes/ViewHelpers/Link/CategoryViewHelper.php, Classes/ViewHelpers/Link/TagViewHelper.php
=> [BUGFIX] LinkViewHelper must set correct controller context

Classes/Domain/Model/Author.php, Classes/Domain/Model/Category.php, Classes/Domain/Model/Tag.php, Classes/Updates/AuthorSlugUpdate.php, Classes/Updates/CategorySlugUpdate.php, Classes/Updates/TagSlugUpdate.php, Configuration/TCA/Overrides/sys_category.php, Configuration/TCA/tx_blog_domain_model_author.php, Configuration/TCA/tx_blog_domain_model_tag.php, Resources/Private/Language/locallang_db.xlf, ext_localconf.php, ext_tables.sql
Releases: master, 9.1, 9.0
Fixes #31
=> [BUGFIX] Introduce path-segments for tags, author and category

Configuration/TypoScript/Static/constants.typoscript, Configuration/TypoScript/Static/setup.typoscript, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/List.html
=> [FEATURE] Make pagination configurable

Classes/Controller/PostController.php, Classes/Controller/WidgetController.php, Classes/Utility/ArchiveUtility.php, Resources/Private/Partials/Archive/Menu.html, Resources/Private/Templates/Post/ListPostsByDate.html, Resources/Private/Templates/Widget/Archive.html
Releases: master, 9.1, 9.0
Fixes: #27
=> [BUGFIX] Resolve endless loop when calling archive without params

Classes/Domain/Repository/PostRepository.php
=> [BUGFIX] Fix language sensitivity of getCurrentPost

Configuration/TCA/Overrides/pages.php
=> [BUGFIX] Allow language synchronization

Classes/Controller/PostController.php
=> [BUGFIX] Fix format detection for feed data

Configuration/TypoScript/Static/setup.txt
=> [BUGFIX] Fix feed page type

Classes/Domain/Repository/PostRepository.php
Fixes: #62
Releases: master, 9.1, 9.0, 8.7, 7.6
=> [BUGFIX] Remove storage constraint from finding current post

Classes/Hooks/DataHandlerHook.php
=> [BUGFIX] Use today as publishing date for new blog entries

Configuration/Extbase/Persistence/Classes.php, ext_typoscript_setup.txt
See: https://forge.typo3.org/issues/87623
Releases: master
=>  [TASK] Replace config.persistence.classes typoscript configuration

Configuration/TypoScript/Static/setup.typoscript, Resources/Private/Partials/General/FlashMessages.html, Resources/Private/Partials/General/FormErrors.html, Resources/Private/Templates/Comment/AddComment.html
=> [BUGFIX] Add severity classes to flash messages

Classes/AvatarProvider/GravatarProvider.php, Classes/AvatarProvider/ImageProvider.php
=> [BUGFIX] Respect configured size in Avatar ImageProvider

Configuration/TCA/Overrides/pages.php
=> [BUGFIX] Disallow multiple assignments of authors to a post

Classes/Domain/Model/Author.php, Configuration/TCA/tx_blog_domain_model_author.php, Resources/Private/Language/locallang_db.xlf, Resources/Private/Partials/Post/Author.html, ext_tables.sql
=> [!!!][TASK] Remove Google Plus after its shutdown

Classes/Controller/PostController.php, Classes/Service/MetaTagService.php, Classes/TitleTagProvider/BlogTitleTagProvider.php, Configuration/TypoScript/Static/setup.typoscript
=> [BUGFIX] Use MetaTag API

Documentation/Administrators/Index.rst
=> [TASK] Add documentation regarding the configuration of storage PIDs

Configuration/DataHandler/BlogSetupRecords.php
Resolves: DEV-675
Releases: 10.0, 9.1, 9.0
=> [BUGFIX] Use noreply as default email address

Configuration/TCA/Overrides/pages.php, Configuration/TCA/tx_blog_domain_model_author.php, Configuration/TCA/tx_blog_domain_model_comment.php, Configuration/TCA/tx_blog_domain_model_tag.php
=> [TASK] Drop redundant TCA definitions

Configuration/Services.yaml
=> Add services configuration

Configuration/TCA/Overrides/sys_category.php
=> [BUGFIX] Prevent renamed categories being detached from non-page records #81

Classes/Factory/PostRepositoryDemandFactory.php
=> [BUGFIX] Remove semicolons from annotations

Classes/ExpressionLanguage/BlogVariableProvider.php
=> [BUGFIX] Catch PHP8 array key warnings

composer.json
Resolves https://github.com/TYPO3GmbH/blog/issues/309
=> [TASK] Allow psr/http-message 1.1 and 2.0

Classes/Controller/BackendController.php, Classes/Domain/Repository/CommentRepository.php, Classes/Domain/Repository/PostRepository.php, Tests/Unit/Service/Avatar/Gravatar/GravatarUriBuilderTest.php
@see https://wiki.php.net/rfc/deprecate-implicitly-nullable-types
=> [TASK] Declare nullable types as nullable explicitly
