TYPO3GmbH/blog

- Classes/Controller/PostController.php
Fixed by casting settings to `int` before passing to a method.
> [BUGFIX] Fix #24: TypyError exception when calling PostRepository::findRelatedPosts()

- Classes/ViewHelpers/Link/ArchiveViewHelper.php
- Classes/ViewHelpers/Link/AuthorViewHelper.php
- Classes/ViewHelpers/Link/CategoryViewHelper.php
- Classes/ViewHelpers/Link/TagViewHelper.php
Fixed by adding `$extensionName` parameter to the uriBuilder call.
> [BUGFIX] Fix #5: tag link viewhelper creates a wrong link outside of EXT:blog plugins

- Resources/Private/Partials/List.html
- Resources/Private/Partials/SimpleList.html
- Resources/Private/Templates/Backend/SocialImageWizard.html
> [BUGFIX] Correct fluid namespace definitions

- Classes/Controller/PostController.php
Fixes: #49 
Releases: master, 9.1, 9.0, 8.7, 7.6
> [BUGFIX] Avoid exception when accessing uninitialized settings

- Classes/Domain/Repository/CommentRepository.php
> [BUGFIX] Only add storage constraint if pages could be resolved

- Resources/Private/Language/locallang.xlf
- Resources/Private/Templates/Post/Sidebar.html
The sidebar headline does not deliver any benefit. The user has the option
to use the title of the content element to add a headline to the sidebar if
nessesary, in general this has no real usecase since only the headlines
of the widgets are relevant.
Releases: master
> [!!!][TASK] Remove obsolete sidebar headline

- Classes/Domain/Model/Post.php
- Classes/Domain/Repository/PostRepository.php
The current implementation also takes translations into
account. This leads to incorrect results for if you have
translated posts, or set a different fallback behavior.
We now also use the Extbase-QueryBuilder for the archive
widget to automatically respect these settings and deliver
the correct results. 
Since TYPO3 8.7 is relying on page_language_overlay,
this problem only occurs in the 9.x and 10.x versions.
Releases: master, 9.1, 9.0
> [BUGFIX] Respect translation settings in archive widget

- Classes/Domain/Model/Post.php
- Tests/Unit/Domain/Model/PostTest.php
Set the correct doktype via the post model. This is required when posts
are created via Extbase, in an action or a command for example.
Fixes #82
> [BUGFIX] Set default doktype for post model

- Configuration/TCA/Overrides/sys_category.php
- Configuration/TCA/tx_blog_domain_model_author.php
- Configuration/TCA/tx_blog_domain_model_tag.php
Fixes #42 by removing wrong `displayCond`.
> [BUGFIX] #42: exception when editing a tag or author

- Classes/Controller/CommentController.php
- Classes/Controller/PostController.php
- Resources/Private/Language/locallang.xlf
- Resources/Private/Layouts/Post.html
- Resources/Private/Templates/Comment/Comments.html
- Resources/Private/Templates/Comment/Form.html
- Resources/Private/Templates/Post/Authors.html
- Resources/Private/Templates/Post/Footer.html
- Resources/Private/Templates/Post/Header.html
- Resources/Private/Templates/Post/Metadata.html
- Resources/Private/Templates/Post/RelatedPosts.html
To prevent the usage of plugins that should only be
used on post views we are now adding additional 
checks for those. If no post could be resolved - also 
means if the plugin is used on pages that do not match
the `Constants::DOKTYPE_BLOG_POST` - the plugins will
now return a new message to make the miss usage visible.
```
A possible configuration error was detected.
No matching post could be obtained. Make sure that this plugin is only used on a post.
```
The following plugins will now show this message if no 
post could be obtained:
* Authors
* Footer
* Header
* Metadata
* RelatedPosts
Templates added:
* Layouts/Post.html
Templates changed:
* Templates/Comment/Comments.html
* Templates/Comment/Form.html
* Templates/Post/Authors.html
* Templates/Post/Footer.html
* …
> [!!!][TASK] Add configuration error note for single view plugins

- Classes/Domain/Repository/PostRepository.php
The calculation of the interval for years is wrong, the list does not show the contributions of a year, rather all contributions older than the current year.
> [BUGFIX] Correct constraint for fetching posts by year

- Configuration/Routes/BlogArchive.yaml
Error message was:
Parameter "tx_blog_archive__year" for route "tx_blog_archive_1" must match "[0-9]{1..4}" ("2020" given) to generate a corresponding URL.
Regex quantifiers are separated by comma, this pull request fixes the issue.
> Fixed invalid regex syntax causing crash on Typo3 10.4.4

- Classes/Domain/Factory/CommentFormFactory.php
Due to an undiscovered breaking change, redirects in the RedirectFinisher
don't work anymore if the pageUid is an integer. This change casts the
pageUid to a string to workaround this new behavior.
See https://review.typo3.org/c/Packages/TYPO3.CMS/+/65467 as well.
> [BUGFIX] Cast pageUid in RedirectFinisher to string

- Classes/ViewHelpers/Link/ArchiveViewHelper.php
If the configuration `plugin.tx_blog.settings.archiveUid` is undefined,
the link to the archive pages cannot be built which causes the
"generation" of the link text only. However, this may fail if only the
year is returned, as it is an integer.
This patch adds a string cast to the rendering result to handle
year-only results as strings as well.
> [BUGFIX] Enforce ArchiveViewHelper to return a string

- Classes/Domain/Factory/CommentFormFactory.php
This reflects its purpose better and does not prevent 3rd party from adding a proper "headline" field to comments.
> Rename comment form explanation hint

- .github/workflows/ci.yml
GitHub boots MySQL v8 in the latest Ubuntu image which is unsupported
with TYPO3 v10 and PHP < 7.4. Due to this, we enforce using MySQL 5.7
in CI for now.
Releases: master, 10
> [BUGFIX] Setup mysql server in docker container

- Classes/Controller/BackendController.php
- Classes/Controller/CommentController.php
- Classes/Controller/PostController.php
- Classes/Controller/WidgetController.php
- Configuration/TCA/tx_blog_domain_model_tag.php
> [BUGFIX] Ensure compatibility between v10 and v11

- .gitattributes
This PR extends `.gitattributes` by the following files to exclude them from dist archives:
* `.php-cs-fixer.dist.php`
* `.phplint.yml`
* `postcss.config.js`
> [BUGFIX] Exclude various dev-only files from dist archives

- Classes/Hooks/DataHandlerHook.php
- Tests/Functional/Hooks/DataHandlerHookTest.php
- Tests/Functional/Hooks/Fixtures/BlogBasePages.csv
Fixes #281
**Explanation:**
In https://github.com/TYPO3GmbH/blog/commit/b77f22dea9a3db4f2d554a23c912089e33ca8f75#diff-62c740cd7ba615b9771602fedd2cab6bc50ac4052c3f8432913f59dbaf3d5effR48 an attempted migration away from the deprecated DBAL `fetch()` method failed. 
Instead of the drop-in replacement `fetchAssociative`, the wrong method `fetchOne` was chosen. 
Maybe the author @benjaminkott had intended to use `fetchOne`, but select the desired field rather than the entire row. (The latter approach is taken by this PR.)
In `v12.0.0` (or at any time after b77f22dea9a3db4f2d554a23c912089e33ca8f75), the database loaded and transmitted the entire row, but only the first column of the first row was returned. (See `Doctrine\DBAL\ForwardCompatibility\Result::fetchOne`, which calls `fetchNumeric` …
> fix: Article publish date is always replaced by current timestamp

- Classes/Routing/Aspect/StaticDatabaseMapper.php
The class `T3G\AgencyPack\Blog\Routing\Aspect\StaticDatabaseMapper` now builds propert conditions in the used SQL query.
> [BUGFIX] Build correct database query in `StaticDatabaseMapper`
